// packages/web-components/src/AccountDashboard.tsx
import ReactDOM from 'react-dom/client'
import { AccountDashboard } from '@nofrixion/components'
import r2wc from 'react-to-webcomponent'
import React from 'react'

const DashBoard = r2wc(AccountDashboard, React, ReactDOM, {
  props: {
    token: 'string',
    apiUrl: 'string',
    accountId: 'string',
    merchantId: 'string',
    onAllCurrentAccountsClick: 'function',
  },
})

customElements.define('account-dashboard', DashBoard)

// apps/business/src/pages/current-accounts/account-dashboard.tsx
import { AccountDashboard } from '@nofrixion/components'
import { useNavigate, useParams } from 'react-router-dom'

import { NOFRIXION_API_URL } from '../../lib/constants'

const AccountDashboardPage = () => {
  const navigate = useNavigate()
  const { accountId } = useParams()

  const onAllCurrentAccountsClick = () => {
    navigate('../current-accounts')
  }

  return (
    <div>
      {accountId && (
        <AccountDashboard
          accountId={accountId}
          apiUrl={NOFRIXION_API_URL}
          onAllCurrentAccountsClick={onAllCurrentAccountsClick}
        />
      )}
    </div>
  )
}

export default AccountDashboardPage
